spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:note;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    contexts: dev
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          cache-public: false

application:
  api-docs:
    title: Note API
    description: Note endpoints with CRUD operations.
    version: 0.0.1
  security:
    jwt:
      # Generate at least a 256-bit secret, e.g. openssl rand -base64 32
      secret: CDyi/yxfK/EMHtj20eOFoLc0t08WVHotnfcpgpnjdt4
      issuer: http://localhost:8080
      audience: note-api
      access-token-ttl: PT30M
      refresh-token-ttl: PT2H
      refresh-token-ttl-for-remember-me: P30D
  cache:
    caffeine:
      ttl: PT1H
      initial-capacity: 50
      maximum-size: 100

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    io.github.susimsek.springdataaotsamples: debug
