spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:note;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  liquibase:
    contexts: dev
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          cache-public: false

security:
  jwt:
    # Generate at least a 256-bit secret, e.g. openssl rand -base64 32
    secret: CDyi/yxfK/EMHtj20eOFoLc0t08WVHotnfcpgpnjdt4
    issuer: http://localhost:8080
    audience: note-api
    access-token-ttl: PT10M
    refresh-token-ttl: P7D

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    io.github.susimsek.springdataaotsamples: debug
