spring:
  application:
    name: spring-data-aot-samples
  profiles:
    active: '@spring.profiles.active@'
  cache:
    type: caffeine
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: Europe/Istanbul
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.fetch_size: 50
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: false
        serialization-mode: via_dto
  messages:
    basename: i18n/messages
  jackson:
    default-property-inclusion: non_null
  web:
    resources:
      chain:
        enabled: true
  threads:
    virtual:
      enabled: true
