version: 2.1

executors:
  jdk:
    docker:
      - image: cimg/openjdk:25.0
    resource_class: medium

  graalvm:
    docker:
      - image: ghcr.io/graalvm/native-image-community:25
    resource_class: large

jobs:
  build:
    executor: jdk
    steps:
      - checkout
      - run:
          name: Git fetch
          command: git fetch --prune --tags --no-filter --refetch
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Print Java Version
          command: java -version
      - run:
          name: Give Executable Power
          command: chmod +x mvnw
      - run:
          name: Install Maven dependencies
          command: ./mvnw -ntp -Pprod dependency:go-offline
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository
      - run:
          name: Test
          command: ./mvnw -B -ntp -Pprod verify
      - run:
          name: Analyze code with SonarQube
          command: |
            if [ -n "${SONAR_TOKEN}" ]; then
              ./mvnw -ntp initialize sonar:sonar \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=susimsek \
                -Dsonar.token=${SONAR_TOKEN}
            else
              echo "SONAR_TOKEN not set, skipping Sonar analysis."
            fi

  docker-push:
    executor: jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Give Executable Power
          command: chmod +x mvnw
      - run:
          name: Package application
          command: ./mvnw -ntp -Pprod -DskipTests package
      - run:
          name: Publish docker image
          command: |
            ./mvnw -ntp -Pprod -DskipTests jib:build \
              -Djib.to.image=docker.io/${DOCKER_USERNAME}/note-app \
              -Djib.to.tags=latest \
              -Djib.to.auth.username="${DOCKER_USERNAME}" \
              -Djib.to.auth.password="${DOCKER_PASSWORD}"

  docker-push-native:
    executor: graalvm
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Give Executable Power
          command: chmod +x mvnw
      - run:
          name: Print GraalVM Version
          command: |
            java -version
            native-image --version
      - run:
          name: Build GraalVM native executable
          command: |
            ./mvnw -ntp -Pprod,native -DskipTests \
              -Dnative-build-args="--verbose -J-Xmx6g" \
              native:compile

workflows:
  build-and-push:
    jobs:
      - build
      - docker-push:
          requires:
            - build
          filters:
            branches:
              only: main
      - approve-native:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: main
      - docker-push-native:
          requires:
            - approve-native
          filters:
            branches:
              only: main
