version: 2.1

executors:
  jdk:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: medium

jobs:
  build:
    executor: jdk
    steps:
      - checkout
      - run:
          name: Git fetch
          command: git fetch --prune --tags --no-filter --refetch
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Print Java Version
          command: java -version
      - run:
          name: Give Executable Power
          command: chmod +x mvnw
      - run:
          name: Install Maven dependencies
          command: ./mvnw -ntp -Pprod dependency:go-offline
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Test
          command: ./mvnw -B -ntp -Pprod verify
      - run:
          name: Analyze code with SonarQube
          command: |
            ./mvnw -ntp initialize sonar:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=susimsek \
              -Dsonar.token=${SONAR_TOKEN}

  docker-push:
    executor: jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Give Executable Power
          command: chmod +x mvnw
      - run:
          name: Publish docker image
          command: |
            ./mvnw -ntp -Pprod -DskipTests verify jib:build \
              -Djib.to.image=docker.io/${DOCKER_USERNAME}/note-app \
              -Djib.to.tags=latest \
              -Djib.to.auth.username="${DOCKER_USERNAME}" \
              -Djib.to.auth.password="${DOCKER_PASSWORD}"

workflows:
  build-and-push:
    jobs:
      - build
      - docker-push:
          requires:
            - build
          filters:
            branches:
              only: main
