version: 2.1

executors:
  jdk:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: medium

jobs:
  build:
    executor: jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-
      - run:
          name: Print Java Version
          command: java -version
      - run:
          name: Build and test
          command: mvn -ntp -Pprod verify
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

  docker-push:
    executor: jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-
      - run:
          name: Jib build & push (latest)
          command: |
            mvn -ntp -Pprod -DskipTests package jib:build \
              -Djib.to.image=docker.io/${DOCKER_USERNAME}/note-app \
              -Djib.to.tags=${CIRCLE_TAG:+${CIRCLE_TAG},}latest \
              -Djib.to.auth.username="${DOCKER_USERNAME}" \
              -Djib.to.auth.password="${DOCKER_PASSWORD}"

workflows:
  build-and-push:
    jobs:
      - build
      - docker-push:
          requires:
            - build
          filters:
            branches:
              only: main
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
