# Dev purpose only. DO NOT use in production.
name: note-app
services:
  app:
    image: ghcr.io/susimsek/note-app:latest-native
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/note
      - SPRING_DATASOURCE_USERNAME=note
      - SPRING_LIQUIBASE_ENABLED=false
      - SECURITY_JWT_SECRET=GOnGieF8gvSk01KtlZUwkpQB8U4tZWTrSt/BJm0+2Mk=
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=0.1
      - MANAGEMENT_OTLP_LOGGING_EXPORT_ENABLED=false
      - MANAGEMENT_TRACING_EXPORT_OTLP_ENABLED=false
      - MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED=false
      - MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://grafana-lgtm:4318/v1/metrics
      - MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/traces
      - MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/logs
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully

  liquibase:
    image: ghcr.io/susimsek/liquibase-postgresql:5.0.1
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://postgresql:5432/note
      - LIQUIBASE_COMMAND_USERNAME=note
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db/master.xml
    volumes:
      - ../resources/config/liquibase:/liquibase/db:ro
    command:
      - update

  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
