# Dev purpose only. DO NOT use in production.
name: note-app
services:
  app:
    image: ghcr.io/susimsek/note-app:latest-native
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/note
      - SPRING_DATASOURCE_USERNAME=note
      - SECURITY_JWT_SECRET=GOnGieF8gvSk01KtlZUwkpQB8U4tZWTrSt/BJm0+2Mk=
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=0.1
      - MANAGEMENT_OTLP_LOGGING_EXPORT_ENABLED=true
      - MANAGEMENT_TRACING_EXPORT_OTLP_ENABLED=true
      - MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED=true
      - MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://grafana-lgtm:4318/v1/metrics
      - MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/traces
      - MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/logs
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
