apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "note-app.fullname" . }}
  labels:
    {{ include "note-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
{{ toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{ include "note-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret-database: {{ include (print $.Template.BasePath "/secret-database.yaml") . | sha256sum }}
        checksum/secret-jwt: {{ include (print $.Template.BasePath "/secret-jwt.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{ include "note-app.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "note-app.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
{{ toYaml . | indent 8 }}
      {{- end }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      initContainers:
        {{- if .Values.initContainers.waitForDb.enabled }}
        - name: wait-for-db
          image: "{{ .Values.initContainers.waitForDb.image.repository }}:{{ .Values.initContainers.waitForDb.image.tag }}"
          imagePullPolicy: {{ .Values.initContainers.waitForDb.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              DATABASE_URL="{{ .Values.spring.datasource.url }}"

              echo "Checking database socket for JDBC URL: $DATABASE_URL"

              case "$DATABASE_URL" in
                jdbc:*://*:*/*)
                  HP=${DATABASE_URL#jdbc:*://}
                  HP=${HP%%/*}
                  DB_HOST=${HP%%:*}
                  DB_PORT=${HP##*:}
                  ;;
                *)
                  echo "SKIP: JDBC URL must be in format jdbc:xxx://host:port/..."
                  echo "Given: $DATABASE_URL"
                  exit 0
                  ;;
              esac

              echo "Waiting for DB $DB_HOST:$DB_PORT"
              until nc -z -w 1 "$DB_HOST" "$DB_PORT"; do
                sleep 5
              done

              echo "DB is UP"
        {{- end }}
        {{- if .Values.initContainers.liquibase.enabled }}
        - name: liquibase
          image: "{{ .Values.initContainers.liquibase.image.repository }}:{{ .Values.initContainers.liquibase.image.tag }}"
          imagePullPolicy: {{ .Values.initContainers.liquibase.image.pullPolicy }}
          args:
            - update
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: {{ .Values.spring.datasource.url | quote }}
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "note-app.fullname" . }}-secret-database
                  key: database-username
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "note-app.fullname" . }}-secret-database
                  key: database-password
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: {{ .Values.initContainers.liquibase.changeLogFile | quote }}
          volumeMounts:
            - name: liquibase-volume
              mountPath: /liquibase/db
              readOnly: true
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.spring.datasource.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "note-app.fullname" . }}-secret-database
                  key: database-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "note-app.fullname" . }}-secret-database
                  key: database-password
            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "note-app.fullname" . }}-secret-jwt
                  key: jwt-secret
          volumeMounts:
            - name: config
              mountPath: /tmp/config/application.yml
              subPath: application.yml
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
            successThreshold: {{ .Values.probes.startup.successThreshold }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "note-app.fullname" . }}
            items:
              - key: application.yml
                path: application.yml
        {{- if .Values.initContainers.liquibase.enabled }}
        - name: liquibase-volume
          configMap:
            name: {{ include "note-app.fullname" . }}-liquibase
            items:
              - key: master.xml
                path: master.xml
              {{- range $path, $_ := .Files.Glob "liquibase/changelog/*.xml" }}
              - key: {{ base $path }}
                path: changelog/{{ base $path }}
              {{- end }}
              {{- range $path, $_ := .Files.Glob "liquibase/data/*.csv" }}
              - key: {{ base $path }}
                path: data/{{ base $path }}
              {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    {{ include "note-app.selectorLabels" . | nindent 20 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
