apiVersion: v1
kind: Secret
metadata:
  name: {{ include "note-app.fullname" . }}-secret-jwt
  labels:
    {{ include "note-app.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.security.jwt.secret | b64enc | quote }}
