apiVersion: v1
kind: Secret
metadata:
  name: {{ include "note-app.fullname" . }}-secret-database
  labels:
    {{ include "note-app.labels" . | nindent 4 }}
type: Opaque
data:
  database-username: {{ .Values.spring.datasource.username | b64enc | quote }}
  database-password: {{ .Values.spring.datasource.password | b64enc | quote }}
