name: Build Native

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v5

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "25"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "maven"
          components: "native-image"
          native-image-musl: "true"

      - name: Print Java & Native Image Version
        run: |
          java --version
          native-image --version

      - name: Give Executable Power
        run: chmod +x mvnw

      - name: Install Maven dependencies
        run: ./mvnw -ntp -Pprod dependency:go-offline

      - name: Test
        run: ./mvnw -B -ntp -Pprod verify

      - name: SonarCloud analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          if [ -n "${SONAR_TOKEN}" ]; then
            ./mvnw -ntp initialize sonar:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=susimsek \
              -Dsonar.token=${SONAR_TOKEN}
          else
            echo "SONAR_TOKEN not set, skipping Sonar analysis."
          fi

      - name: Install UPX
        run: |
          set -e
          UPX_VERSION=5.0.2
          UPX_ARCHIVE=upx-${UPX_VERSION}-amd64_linux.tar.xz

          wget -q https://github.com/upx/upx/releases/download/v${UPX_VERSION}/${UPX_ARCHIVE}
          tar -xJf ${UPX_ARCHIVE}
          sudo mv upx-${UPX_VERSION}-amd64_linux/upx /usr/local/bin/upx
          sudo chmod +x /usr/local/bin/upx

          # cleanup
          rm -rf ${UPX_ARCHIVE} upx-${UPX_VERSION}-amd64_linux

          upx --version

      - name: Build GraalVM native executable
        run: |
          ./mvnw -ntp -Pprod,native -DskipTests \
            -DbuildArgs="--no-fallback,-Os,--static,--libc=musl,--verbose,-J-Xmx6g" \
            native:compile

      - name: Compress native executable with UPX
        run: upx --lzma --best target/native-executable

      - name: Publish docker image
        if: github.ref == 'refs/heads/main'
        run: |
          ./mvnw -ntp -Pprod,native -DskipTests \
            jib:build \
            -Djib.to.image=ghcr.io/${{ github.repository_owner }}/note-app:latest-native \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
